CREATE DATABASE IF NOT EXISTS devbook;
USE devbook;

DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS followers;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  NICK VARCHAR(50) NOT NULL UNIQUE,
  EMAIL VARCHAR(50) NOT NULL UNIQUE,
  PASSWORD VARCHAR(100) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE followers(
  USER_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE,
  FOLLOWER_ID INT NOT NULL,
  FOREIGN KEY (FOLLOWER_ID) REFERENCES users(ID) ON DELETE CASCADE,
  PRIMARY KEY (USER_ID, FOLLOWER_ID)
) ENGINE=INNODB;

CREATE TABLE posts(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(50) NOT NULL,
  CONTENT VARCHAR(300) NOT NULL,
  AUTHOR_ID INT NOT NULL,
  FOREIGN KEY (AUTHOR_ID) REFERENCES users(ID) ON DELETE CASCADE,
  LIKES INT DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;
